// Declarative Pipeline
pipeline {
    agent any

    stages {
        stage('Stop') {
            steps {
                echo 'Stop Stage'
            }
        }
        stage('Build') {
            steps {
                echo 'Build Stage'
             }
        }
        stage('Start') {
            steps {
                echo 'Start Stage'
            }
        }
    }
}
