// Declarative Pipeline
pipeline {
    agent none

    stages {
        stage('Build') {
            steps {
                sh '''#!/bin/bash
                        echo $SHELL
                        docker build --tag=local/ubuntu:casc .
                '''
             }
        }
        stage('Image List') {
            steps {
                sh '''#!/bin/bash
                      echo $SHELL
                '''
            }
        }
    }
}
