// Declarative Pipeline
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''#!/bin/bash
                        echo $SHELL
                        docker build --tag=local/ubuntu:casc .
                '''
             }
        }
        stage('Image List') {
            steps {
                bash '''
                docker images
                '''
            }
        }
    }
}
