---
version: "2"

volumes:
  app:
  db:

services:
  db:
    image: mariadb:10.5
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:casc
    build:
      context: .
      args:
        - EMAIL="${EMAIL}"
        - DOMAIN="${DOMAIN}"
    container_name: nextcloud_app
    restart: unless-stopped
      - 80:80
      - 443:443
    links:
      - db
    volumes:
      - app:/var/www/html
      - "${SSL_DIR}:/etc/ssl/nextcloud"
    environment:
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
