---
version: "3"
volumes:
  home:

services:
  app:
    image: jenkins:casc
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
